# Generated by Django 5.2.5 on 2025-11-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_pedido_cliente_remove_pedido_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('numero_pedido', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('direccion_entrega', models.TextField()),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas_cliente', models.TextField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(default='tarjeta transbank', max_length=50)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('detalle_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.pedido')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoDespacho',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('seguimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='orders.pedido')),
            ],
            options={
                'db_table': 'seguimiento_despacho',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TamanoPredefinido',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tamano_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tamano', models.CharField(max_length=100)),
                ('ancho_cm', models.PositiveIntegerField()),
                ('alto_cm', models.PositiveIntegerField()),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanos_predefinidos', to='core.producto')),
            ],
            options={
                'db_table': 'tamanos_predefinidos',
            },
        ),
    ]
