# Generated by Django 5.2.5 on 2025-11-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pedido_cliente_remove_pedido_user_profile_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='acabado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='core.acabado'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='archivo_diseno',
            field=models.URLField(blank=True, help_text='URL del archivo de diseño subido', null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='costo_acabado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='costo_tiempo_produccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='dias_produccion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_acabado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_tiempo_produccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='notas_producto',
            field=models.TextField(blank=True, help_text='Notas específicas de este producto', null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='personalizacion_texto',
            field=models.TextField(blank=True, help_text='Texto personalizado del cliente', null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='tiempo_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='core.tiempoproduccion'),
        ),
    ]
