# Generated by Django 5.2.5 on 2025-11-01 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pedido_cliente_remove_pedido_user_profile_and_more'),
        ('orders', '0002_detallepedido_acabado_detallepedido_archivo_diseno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='costo_terminacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_terminacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='terminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='core.terminacion'),
        ),
    ]
