# Generated by Django 5.2.5 on 2025-11-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_detallepedido_costo_terminacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='archivo_diseno',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='archivo_cara1',
            field=models.CharField(blank=True, help_text='Ruta del archivo cara 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='archivo_cara2',
            field=models.CharField(blank=True, help_text='Ruta del archivo cara 2', max_length=500, null=True),
        ),
    ]
