# Generated by Django 5.2.5 on 2025-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_detallepedido_archivo_diseno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='costo_terminacion',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='costo_tiempo_produccion',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
