# Generated by Django 5.2.5 on 2025-10-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_por_mayor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_por_mayor',
            field=models.IntegerField(blank=True, default=0, help_text='Cantidad mínima para precio por mayor', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ventas_totales',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vistas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
