# Generated by Django 5.2.5 on 2025-10-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acabado',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('acabado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_acabado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_adicional', models.PositiveIntegerField(blank=True, default=0, help_text='Costo adicional por este acabado', null=True)),
            ],
            options={
                'verbose_name': 'Acabado',
                'verbose_name_plural': 'Acabados',
                'db_table': 'acabados',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('acabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_acabados', to='core.acabado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_acabados', to='core.producto')),
            ],
            options={
                'verbose_name': 'Acabado del Producto',
                'verbose_name_plural': 'Acabados del Producto',
                'db_table': 'productos_acabados',
                'unique_together': {('producto', 'acabado')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='acabados',
            field=models.ManyToManyField(blank=True, related_name='productos', through='core.ProductoAcabado', to='core.acabado'),
        ),
        migrations.CreateModel(
            name='Terminacion',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('terminacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_terminacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.PositiveIntegerField(blank=True, default=0, help_text='Precio final con esta terminación', null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminaciones', to='core.producto')),
            ],
            options={
                'verbose_name': 'Terminación',
                'verbose_name_plural': 'Terminaciones',
                'db_table': 'terminaciones',
            },
        ),
        migrations.CreateModel(
            name='TiempoProduccion',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tiempo_produccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tiempo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dias_estimados', models.PositiveIntegerField(help_text='Días estimados de producción')),
                ('precio', models.PositiveIntegerField(blank=True, default=0, help_text='Precio final con este tiempo de producción', null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_produccion', to='core.producto')),
            ],
            options={
                'verbose_name': 'Tiempo de Producción',
                'verbose_name_plural': 'Tiempos de Producción',
                'db_table': 'tiempos_produccion',
            },
        ),
    ]
