# Generated by Django 5.2.5 on 2025-09-13 02:12

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ciudad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('codigo_ciudad', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=100)),
                ('codigo_pais', models.CharField(max_length=5)),
                ('codigo_iso', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('documento_identidad', models.CharField(max_length=15, unique=True)),
                ('dv', models.CharField(max_length=1, verbose_name='Dígito Verificador')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('cod_tel_pais', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_telefono', models.CharField(blank=True, max_length=5, null=True)),
                ('telefono_persona', models.CharField(blank=True, max_length=15, null=True)),
                ('cod_tel_pais_wp', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_tel_wp', models.CharField(blank=True, max_length=5, null=True)),
                ('whatsapp_persona', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='RegistroPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('datos_serializados', models.JSONField()),
                ('email', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expiracion', models.DateTimeField()),
            ],
            options={
                'db_table': 'registros_pendiente',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('codigo_rol', models.CharField(max_length=10, unique=True)),
                ('descripcion_rol', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_direccion', models.CharField(max_length=50)),
                ('codigo_tipo_direccion', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Dirección',
                'verbose_name_plural': 'Tipos de Dirección',
                'db_table': 'tipos_direccion',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('unidad_medida_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad_medida', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='VisitaPagina',
            fields=[
                ('visita_pagina_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('ruta', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visitas_pagina',
            },
        ),
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='carrusel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item de Carrito', 'verbose_name_plural': 'Items de Carrito'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='preguntafrecuente',
            options={'ordering': ['orden', 'pregunta'], 'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': 'Preguntas Frecuentes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={},
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='fecha_actualizacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='destacado',
            new_name='es_destacado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_actualizacion',
            new_name='fecha_modificacion',
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='novedad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='carrito',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='sesion_id',
            field=models.CharField(blank=True, help_text='ID de sesión para usuarios no autenticados', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='color_fondo',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrusel',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='link_boton',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='texto_boton',
            field=models.CharField(default='Ver más', max_length=30),
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='codigo_popular',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='es_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(default='defecto', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='defecto', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_interaccion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='categoria',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('productos', 'Productos'), ('envios', 'Envíos'), ('pagos', 'Pagos'), ('devoluciones', 'Devoluciones')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='detalle_producto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_insumo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_oferta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto_10pc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(default='defecto', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_neto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_estante_bodega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_por_mayor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_unidad_por_mayor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='nombre_subcategoria',
            field=models.CharField(default='defecto', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carruseles/'),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='pregunta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AlterModelTable(
            name='carrito',
            table='carritos',
        ),
        migrations.AlterModelTable(
            name='carrusel',
            table='carruseles',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='detalles_pedido',
        ),
        migrations.AlterModelTable(
            name='itemcarrito',
            table='items_carrito',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AlterModelTable(
            name='preguntafrecuente',
            table='preguntas_frecuentes',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='subcategorias',
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('comuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
                ('codigo_comuna', models.CharField(max_length=5)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comunas',
            },
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('calle_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=150)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comuna')),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
                'db_table': 'calles',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('localizacion_google', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_numero', models.CharField(max_length=10)),
                ('direccion_depto', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_block', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_referencia', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('calle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.calle')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comuna')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direcciones', to='core.persona')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direcciones',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direccion'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('imagen_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.core.models.producto_imagen_path)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='core.producto')),
            ],
            options={
                'db_table': 'imagenes_productos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca'),
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('iva_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais')),
            ],
            options={
                'db_table': 'ivas',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.persona'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
                ('codigo_region', models.CharField(max_length=5)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pais')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'regiones',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='tipo_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodireccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadmedida'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('user_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_verified', models.BooleanField(default=False)),
                ('token_validacion', models.CharField(blank=True, max_length=100, null=True)),
                ('persona', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil', to='core.persona')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('sesion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'db_table': 'sesiones_usuario',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='nombre',
        ),
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('user_rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rol')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'users_roles',
                'unique_together': {('user_profile', 'rol')},
            },
        ),
    ]
