# Generated by Django 5.2.5 on 2025-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo_ciudad_marca_pais_persona_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='color_fondo',
            field=models.CharField(blank=True, default='#2563eb', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='link_boton',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='texto_boton',
            field=models.CharField(blank=True, default='Ver más', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
