# Generated by Django 5.2.5 on 2025-10-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acabado_productoacabado_producto_acabados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamanoPredefinido',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tamano_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tamano', models.CharField(max_length=100)),
                ('ancho_cm', models.PositiveIntegerField()),
                ('alto_cm', models.PositiveIntegerField()),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanos_predefinidos', to='core.producto')),
            ],
            options={
                'db_table': 'tamanos_predefinidos',
            },
        ),
    ]
