# Generated by Django 5.2.5 on 2025-10-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_precio_por_mayor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito Verificador'),
        ),
    ]
