# Generated by Django 5.2.5 on 2025-11-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_persona_documento_identidad_alter_persona_dv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='seguimientodespacho',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='tamanopredefinido',
            name='producto',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='SeguimientoDespacho',
        ),
        migrations.DeleteModel(
            name='TamanoPredefinido',
        ),
    ]
