# Generated by Django 5.2.5 on 2025-10-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tamanopredefinido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminacion',
            options={'ordering': ['orden', 'nombre_terminacion'], 'verbose_name': 'Terminación', 'verbose_name_plural': 'Terminaciones'},
        ),
        migrations.AlterModelOptions(
            name='tiempoproduccion',
            options={'ordering': ['orden', 'dias_estimados'], 'verbose_name': 'Tiempo de Producción', 'verbose_name_plural': 'Tiempos de Producción'},
        ),
        migrations.AddField(
            model_name='terminacion',
            name='es_predeterminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terminacion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiempoproduccion',
            name='es_predeterminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiempoproduccion',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
