# Generated by Django 5.2.5 on 2025-11-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pedido_cliente_remove_pedido_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_por_mayor',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
