# Generated by Django 5.2.5 on 2025-10-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_terminacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoacabado',
            options={'ordering': ['orden'], 'verbose_name': 'Acabado del Producto', 'verbose_name_plural': 'Acabados del Producto'},
        ),
        migrations.AddField(
            model_name='productoacabado',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
