# Generated by Django 5.2.5 on 2025-10-28 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('product_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='product_files/')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'archivos_de_productos',
            },
        ),
    ]
